name: documentation

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build documentation and commit
      run: |
          git pull
          sudo apt-get install python3-sphinx
          sphinx-apidoc -F -o ./staging ./src
          sphinx-build -b html ./staging ./docs
          git config --global user.name "guptabhishek785"
          git config --global user.email "guptabhishek785@gmail.com"
          git add ./docs
          git commit -m "[Automated] Update docs" -a || true
          git push
